<style>
    .footer{
        padding-top: 40px;
    }
    .f-img img{
        position: absolute;
    }
    .footer_bottom{
        position: relative;
        margin-top: 30px;
        /*padding: 50px 0;*/
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr 1fr;
        /*background-color: #1c404e;*/
        color: white;
    }
</style>
<div class="footer">
    <div class="f-img">
        <img src="<?php echo $this->getViewFileUrl('images/footer.png'); ?>" alt="">
    </div>
    <div class="footer_bottom text-center">
        <div>
            <h3>CONTENT</h3>
            <p>Lorem ipsum </p>
            <p>Dolor sit</p>
        </div>

        <div>
            <h3>INFORMATION</h3>
            <p>Lorem ipsum</p>
            <p>Abcdefghi jklmn</p>
        </div>

        <div>
            <h3>LEGAL</h3>
            <p>Lorem ipsum</p>
            <p>asfdgahsj asdasj</p>
            <p>asfdgahsj asdasj</p>
        </div>

        <div>
            <h3>HELP</h3>
            <p>Lorem ipsum</p>
            <p>asfdgahsj asdasj</p>
        </div>

        <div>
            <h3>CONTENT</h3>
            <i class="fa fa-phone"></i>
        </div>

    </div>
<!--    <div class="end_f">-->
<!---->
<!--    </div>-->
</div>
