<style>
    .nav-bar{
        padding-top: 121px;
        width: 100%;
    }
    .company{
        position: absolute;
        float: left;
        padding-top: 540px;
        padding-left: 930px;
    }
    .company h1{
        color: white;
    }
    .company h2{
        color: #d7794a;
        font-size: 2.3rem !important;
        margin-top: -3.5rem !important;
    }
</style>
<div class="company">
    <h1><b>WELCOME TO</b></h1>
    <h2><b>YOUR COMPANY NAME</b></h2>
</div>
<nav class="nav-bar">
    <ul>
        <li><a href="">Home</a></li>
        <li><a href="">About</a></li>
        <li><a href="">Services</a></li>
        <li><a href="">Testimonials</a></li>
        <li><a href="">Portfolio</a></li>
        <li><a href="">Contact</a></li>
    </ul>
</nav>

<div class="banner">
    <img src="<?php echo $this->getViewFileUrl('images/banner.png'); ?>" alt="">
</div>


