<?php
    $users = $block->GetBlog();
?>

<style>
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
</style>
<table>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Email</th>
        <th>Image</th>
        <th>Created At</th>
        <th>Action</th>
    </tr>
    <?php foreach ($users as $user) { ?>
    <tr>
        <td><?= $user->getData('id') ?></td>
        <td><?= $user->getData('name') ?></td>
        <td><?= $user->getData('email') ?></td>
        <td><a target="_blank" href="<?= $block->getBaesUrl() . $user->getData('image') ?>"><?= $user->getData('image') ?></a></td>
        <td><?= $user->getData('create_at') ?></td>
        <td>
            <button><a href="<?php echo $block->getUrl('haru/index/update').'id/'.$user->getData('id'); ?>">Edit</a></button>
            <button><a href="<?php echo $block->getUrl('haru/index/delete').'?id='.$user->getData('id'); ?>">Delete</a></button>
        </td>
    </tr>
    <?php } ?>
</table>
<br>
<button><a href="<?php echo $block->getUrl('haru/index/create') ?>">Add New User</a></button>

