

<form action="<?= $block->getBaseUrl() . 'hello/index/save' ?>" method="post">
    <label for="">Title</label>
    <input type="text" name="title">
    <label for="">Summary</label>
    <input type="text" name="summary">
    <label for="">Description</label>
    <input type="text" name="description">
    <label for="">Status</label>
    <select name="status" id="">
        <option value="1">1</option>
        <option value="0">0</option>
    </select>
    <label for=""></label>
    <input type="hidden" name="create_at" value="<?= date('Y-m-d H:i:s') ?>">
    <input type="submit" value="Create">
</form>
<br>
<a href="<?php echo $block->getUrl('hello/index/view') ?>">Back</a>
