<?php
namespace Product\SampleAttribute\Model\Attribute\Backend;

use Magento\Bundle\Model\Product;
use Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend;
use Magento\Framework\Exception\LocalizedException;

class Material extends AbstractBackend
{
//    public function validate($object)
//    {
//        $value = $object->getData($this->getAttribute()->getAttributeCode());
//
//        return parent::validate($object); // TODO: Change the autogenerated stub
//    }
}
